apiVersion: v1
version: 6.9.2
appVersion: 6.9.2
name: podinfo
engine: gotpl
description: Podinfo Helm chart for Kubernetes
home: https://github.com/Derankatinum/podinfo
maintainers:
  - email: bholovchak98@gmail.com
    name: derankatinum
sources:
  - https://github.com/Derankatinum/podinfo
kubeVersion: ">=1.23.0-0"
